use std::collections::HashMap;

use crate::resolver::ResolvedPlugin;

/// Compute a stable SHA-256 hex digest of the manifest content.
/// Stored in the lock file header so we can detect when `plugins.txt` changes.
pub fn manifest_hash(content: &str) -> String {
    // Use a simple but stable FNV-64 hash encoded as hex — good enough for
    // staleness detection (not a cryptographic use case).
    let mut hasher = FnvHasher::default();
    hasher.write(content.as_bytes());
    format!("{:016x}", hasher.finish())
}

/// FNV-1a 64-bit hasher — zero-dependency, deterministic across runs.
#[derive(Default)]
struct FnvHasher(u64);

impl FnvHasher {
    fn write(&mut self, bytes: &[u8]) {
        let mut hash: u64 = 14695981039346656037;
        for &b in bytes {
            hash ^= u64::from(b);
            hash = hash.wrapping_mul(1099511628211);
        }
        self.0 = hash;
    }
    fn finish(&self) -> u64 {
        self.0
    }
}

/// Render the resolved plugin map as a `plugins-lock.txt` string.
///
/// Format:
/// ```
/// # Generated by jpm — do not edit manually
/// # Jenkins: 2.452.4
/// # manifest-hash: a3f1b2c4d5e6f7a8
/// #
/// # name:version sha256:<hex>
/// git:5.7.0 sha256:abc123...
/// credentials:1415.v831096eb_5534 sha256:def456...
/// ```
///
/// Plugins are sorted alphabetically so the file diffs cleanly in git.
/// Integrity checksums are included when available from the Update Center.
pub fn render(
    plugins: &HashMap<String, ResolvedPlugin>,
    jenkins_version: &str,
    manifest_content: &str,
) -> String {
    let mut out = String::with_capacity(plugins.len() * 64);

    out.push_str("# Generated by jpm — do not edit manually\n");
    out.push_str(&format!("# Jenkins: {jenkins_version}\n"));
    out.push_str(&format!(
        "# manifest-hash: {}\n",
        manifest_hash(manifest_content)
    ));
    out.push('\n');

    let mut sorted: Vec<&ResolvedPlugin> = plugins.values().collect();
    sorted.sort_by_key(|p| &p.name);

    for plugin in sorted {
        let checksum = plugin
            .sha256
            .as_deref()
            .map(|h| format!(" sha256:{h}"))
            .unwrap_or_default();
        out.push_str(&format!("{}:{}{checksum}\n", plugin.name, plugin.version));
    }

    out
}

/// Parse a `plugins-lock.txt` file back into a map of `name → (version, sha256)`.
/// Lines starting with `#` and blank lines are ignored.
#[allow(dead_code)]
pub fn parse(content: &str) -> HashMap<String, (String, Option<String>)> {
    content
        .lines()
        .filter(|l| !l.starts_with('#') && !l.trim().is_empty())
        .filter_map(|line| {
            // Split on whitespace to separate `name:version` from optional `sha256:...`
            let mut fields = line.splitn(2, ' ');
            let nv = fields.next()?.trim();
            let sha256 = fields
                .next()
                .and_then(|f| f.trim().strip_prefix("sha256:"))
                .map(str::to_owned);

            let mut parts = nv.splitn(2, ':');
            let name = parts.next()?.trim().to_string();
            let version = parts.next()?.trim().to_string();
            Some((name, (version, sha256)))
        })
        .collect()
}

/// Extract the `manifest-hash` header value from a lock file, if present.
pub fn parse_manifest_hash(content: &str) -> Option<String> {
    content.lines().find_map(|line| {
        line.strip_prefix("# manifest-hash: ")
            .map(|h| h.trim().to_string())
    })
}

/// Extract the `Jenkins` header value from a lock file, if present.
pub fn parse_jenkins_version(content: &str) -> Option<String> {
    content.lines().find_map(|line| {
        line.strip_prefix("# Jenkins: ")
            .map(|v| v.trim().to_string())
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_plugin(name: &str, version: &str, sha256: Option<&str>) -> ResolvedPlugin {
        ResolvedPlugin {
            name: name.to_string(),
            version: version.to_string(),
            sha256: sha256.map(str::to_owned),
            is_direct: true,
        }
    }

    #[test]
    fn render_and_parse_roundtrip() {
        let mut plugins = HashMap::new();
        plugins.insert(
            "git".to_string(),
            make_plugin("git", "5.7.0", Some("aabbccdd")),
        );
        plugins.insert(
            "credentials".to_string(),
            make_plugin("credentials", "1415.v831096eb_5534", None),
        );

        let rendered = render(&plugins, "2.452.4", "git\ncredentials\n");
        assert!(rendered.contains("git:5.7.0 sha256:aabbccdd"));
        assert!(rendered.contains("credentials:1415.v831096eb_5534\n"));

        let parsed = parse(&rendered);
        assert_eq!(parsed["git"].0, "5.7.0");
        assert_eq!(parsed["git"].1.as_deref(), Some("aabbccdd"));
        assert_eq!(parsed["credentials"].0, "1415.v831096eb_5534");
        assert!(parsed["credentials"].1.is_none());
    }

    #[test]
    fn alphabetical_ordering() {
        let mut plugins = HashMap::new();
        for name in &["zebra", "alpha", "mango"] {
            plugins.insert(name.to_string(), make_plugin(name, "1.0", None));
        }
        let rendered = render(&plugins, "2.452.4", "");
        let names: Vec<&str> = rendered
            .lines()
            .filter(|l| !l.starts_with('#') && !l.is_empty())
            .collect();
        assert_eq!(names, vec!["alpha:1.0", "mango:1.0", "zebra:1.0"]);
    }

    #[test]
    fn manifest_hash_is_stable() {
        let h1 = manifest_hash("git\ncredentials\n");
        let h2 = manifest_hash("git\ncredentials\n");
        assert_eq!(h1, h2);
    }

    #[test]
    fn manifest_hash_differs_on_change() {
        let h1 = manifest_hash("git\ncredentials\n");
        let h2 = manifest_hash("git\ncredentials\ndocker\n");
        assert_ne!(h1, h2);
    }

    #[test]
    fn parse_manifest_hash_roundtrip() {
        let plugins: HashMap<String, ResolvedPlugin> = HashMap::new();
        let manifest = "git\ncredentials\n";
        let rendered = render(&plugins, "2.452.4", manifest);
        let extracted = parse_manifest_hash(&rendered).unwrap();
        assert_eq!(extracted, manifest_hash(manifest));
    }

    #[test]
    fn parse_jenkins_version_roundtrip() {
        let plugins: HashMap<String, ResolvedPlugin> = HashMap::new();
        let rendered = render(&plugins, "2.452.4", "git\n");
        let extracted = parse_jenkins_version(&rendered).unwrap();
        assert_eq!(extracted, "2.452.4");
    }
}
